# Generated by Django 4.2.3 on 2023-07-09 04:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Elevator",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("serial_number", models.UUIDField(default=uuid.uuid4)),
                ("number", models.PositiveIntegerField(db_index=True, null=True)),
                ("is_operational", models.BooleanField(default=True)),
                ("is_running", models.BooleanField(default=False)),
                ("current_floor", models.IntegerField(default=0)),
                ("destination_floor", models.IntegerField(null=True)),
                ("is_maintenance", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("UP", "UP"), ("DOWN", "DOWN"), ("IDLE", "IDLE")],
                        default="IDLE",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("floor", models.IntegerField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "elevator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_requests",
                        to="elevator.elevator",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
